<?php
declare(strict_types=1);


namespace backend\controllers;


class AdminController extends BaseController
{
    public function init() {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function actionIndex()
    {
        var_dump('admin/index');die;
    }
}
